
notepad c:\Windows\System32\WindowsPowerShell\v1.0\DotNetTypes.format.ps1xml

#Identify the Type of Process Object and search it in the DotNetTypes.format.ps1xml

Notepad C:\Windows\System32\WindowsPowerShell\v1.0\types.ps1xml

#Identify the type of Output generated by get-wmiobject Win32_operatingsystem and search it in the types.ps1xml

#Using Custom Formatting System
$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;background-color: #6495ED;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"

Get-Process | Sort -Property PM -Descending|select `
            @{Name ="Processname"; Expression={$_.Name}},`
            @{Name ="VM (MB)"; Expression={$_.vm/1MB -as [int]}},`
            @{Name ="PM (MB)"; Expression={$_.Pm/1MB -as [int]}},NPM -First 10 | 
            ConvertTo-Html -Title "Highest PM Consuiming Processes"  -Body $a | Out-file C:\Users\Supercoach\Desktop\process..html

## Just in case if you want to show the values in decimal points 
Get-Process | Sort CPU -Descending |Select-Object ProcessName,@{l='cpu';e={[math]::Round($_.cpu,3)}}

@{Name ="PM (MB)"; Expression={$_.Pm/1MB -as [int]}}
@{N ="PM (MB)"; E={$_.Pm/1MB -as [int]}}
@{Label="PM (MB)"; E={$_.Pm/1MB -as [int]}}
@{Name ="Processname"; Expression={$_.Name}}

$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"

Get-WmiObject Win32_logicaldisk | where {$_.drivetype -eq 3} | 
                    select deviceid, @{Name ="Drivename"; E={$_.DeviceID}},
                    @{Name ="Freespace"; E ={$_.freespace/1GB -as [int]}},
                    @{Name ="TotalSize"; E ={$_.Size/1GB -as [int]}},
                    @{Name ="%Free"; E ={($_.freespace/$_.Size) * 100 -as [int]}} | 
                    ConvertTo-Html -Head "<H2> Diskspace Report<H2>" -Body $a | out-file C:\Users\Supercoach\Desktop\diskspace.htm


<#
$a = "<style>"
$a = $a + "TABLE{border-width: 1px;border-style: solid;border-color: black;border-collapse: collapse;}"
$a = $a + "TH{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "TD{border-width: 1px;padding: 10px;border-style: solid;border-color: black;}"
$a = $a + "</style>"
#>
$body = Get-Process | select Name,PM,NPM,handle,CPU,WS,ID |`ConvertTo-Html -Head "<H2> Process Status <H2>" -Body $a| `
Format-Table -AutoSize -Wrap | Out-File Process.htm

Send-MailMessage -To -From -Subject -Body $body -SmtpServer

Get-Process | Format-Wide -Property vm -Column 2

Get-Process | Format-Wide -Property name -Column 3

Get-Process -Name Notepad | Format-List -Property *

Get-Process | Format-List -GroupBy Name

##Custom Columns

Get-Process | Sort-Object -Property PM -Descending|`
Select Name, ID,vm, @{Name ="VM(GB)"; Expression={$_.VM /1mB -as [INT]}},`
 @{Name ="PM(MB)"; Expression={$_.PM /1MB -as [INT]}},@{Name ="WS(GB)";`
  Expression={$_.WS /1MB -as [INT]}} -First 10 | ft -AutoSize


Get-Process | Sort-Object -Property Vm -Descending|Select Name, ID, @{Name ="VM(GB)"; Expression={$_.VM /1GB -as [INT]}}, @{Name ="PM(MB)"; Expression={$_.PM /1MB -as [INT]}},@{Name ="WS(GB)"; Expression={$_.WS /1MB -as [INT]}} -First 10 | ft -AutoSize 


##Going Out

Out-file -FilePath c:\temp\Services.txt

Out-Printer -Name 

Out-Default


Get-Process| ?{$_.Name -like "a*"} |format-table -AutoSize 

